apiVersion: v1
kind: Service
metadata:
  name: pitstop-gateway-service
  namespace: pitstop
spec:
  selector:
    app: pitstop-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort