apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitstop-gateway-depl
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pitstop-gateway
  template:
    metadata:
      labels:
        app: pitstop-gateway
    spec:
      containers:
        - name: pitstop-gateway
          image: chaimaaitali/pitstop-express-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: CRYPTO_CIPHER_KEY
              valueFrom:
                secretKeyRef:
                  name: pitstop-gateway-secrets
                  key: CRYPTO_CIPHER_KEY
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: pitstop-gateway-secrets
                  key: SESSION_SECRET
            - name: ACCESS_TOKENS_EXPIRY
              valueFrom:
                secretKeyRef:
                  name: pitstop-gateway-secrets
                  key: ACCESS_TOKENS_EXPIRY
            - name: REFRESH_TOKENS_EXPIRY
              valueFrom:
                secretKeyRef:
                  name: pitstop-gateway-secrets
                  key: REFRESH_TOKENS_EXPIRY
            - name: AUTH_CODES_EXPIRY
              valueFrom:
                secretKeyRef:
                  name: pitstop-gateway-secrets
                  key: AUTH_CODES_EXPIRY
