apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitstop-gateway-depl
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pitstop-gateway
  template:
    metadata:
      labels:
        app: pitstop-gateway
    spec:
      containers:
        - name: pitstop-gateway
          image: chaimaaitali/pitstop-express-gateway:0ca1bf0a
          ports:
            - containerPort: 8080
